worker_processes 1;
events { worker_connections 1024; }
http {
    include      mime.types;
    default_type application/octet-stream;
    sendfile     on;
    keepalive_timeout 65;
    client_body_buffer_size 1m;

    server {
        listen 8080 sndbuf=65536;
        server_name localhost;

        root /data/data/com.termux/files/home/www;
        index index.html;

        auth_basic "Citrus Homelab";
        auth_basic_user_file /data/data/com.termux/files/home/www/.htpasswd;

        location /cam/ {
            proxy_pass http://127.0.0.1:41737/mjpeg;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_cache off;
            proxy_read_timeout 300s;
            proxy_send_timeout 300s;
            proxy_set_header Connection '';
            proxy_set_header Host $host;
            chunked_transfer_encoding off;
        }

        location /lenscast/ {
            proxy_pass http://127.0.0.1:41737/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_buffering off;
        }

        location /files/ {
            proxy_pass http://127.0.0.1:8081/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_buffering off;
            proxy_read_timeout 300s;
        }

        location /api/ {
            proxy_pass http://127.0.0.1:8082/api/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Connection '';
            proxy_buffering off;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}